NEWS = "17a13f729cd74fc58ffb0e4ea995e31d"

OAI = "kSUgb8mtCunsqwsm8wHRT3BlbkFJs1e0oF1O5JeyuJDssRVt"

[mongo]
host_dev = "localhost"
host = "mongodb"
port = 27017
username = "xxx"
password = "xxx"
server = "ServerApi(1)"

[colls]


