NEWS = "17a13f729cd74fc58ffb0e4ea995e31d"

OAI = "kSUgb8mtCunsqwsm8wHRT3BlbkFJs1e0oF1O5JeyuJDssRVt"

[theme]
primaryColor="#3d2d92"
backgroundColor="#b348ea"
secondaryBackgroundColor="#283579"
textColor="#f7f3f6"


[mongo]
host_dev = "localhost"
host = "mongodb"
port = 27017
username = "xxx"
password = "xxx"
server = "ServerApi(1)"

[colls]


