NEWS = "17a13f729cd74fc58ffb0e4ea995e31d"

OAI = "kSUgb8mtCunsqwsm8wHRT3BlbkFJs1e0oF1O5JeyuJDssRVt"

[mongo]
host_dev = "localhost"
host = "mongodb"
port = 27017
username = "xxx"
password = "xxx"
server = "ServerApi(1)"

[colls]


[firebase]
type = "service_account"
project_id = "streamlit-quiz"
private_key_id = "9be928abd29aad02ba178308b62f12e7e5b60334"
private_key = """
-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2Ejw4ZV5dUXqW\ngtfP9m0tcrtMMdTFGGSC9xB4Cx1PYOBiDNvCV/u5VMnr3HJU83qYfB6UfbV+Dsap\nveHf+5KLxVCGfdGbau4KFEGfWQ2mWWtwFw7pp7+TWpPKLqctMk+yC2nxqrFYuC6N\n1zgsPNxwswrNbI0d6DJpjAJRLKoeZyFmp+ATSlZv58z6FfBB+my2prriEchGcW9v\nzGyqYS1/uH15wokhdEYLmA68U/GZ0X1ViTaE5mC+zcPwWPwPTcPfGT3gtuiNnB6a\nB5SYy/oXxRETdfnACr2dr7Rj9Op7YD24cApKlV6x4KI7oSa1WFbWyUPUt5W/6iT6\nn2asOkWBAgMBAAECggEAB+m/pPKAPm1gdugq5Fv2dMeMF7dWuFY4usRtenopL55V\n7OJYLsMk1UeNGxYoAJnbFdjXJLxYm1OdvhowQKGDcKsGYUIDTnjq7ZSMdut86gzw\nMXKfGvfycz9i4Ez/cQ8YYvRCCix8AWTH3ob1vF53dOJ4hrhquFuzd942P5GXDIkm\nJRYNnMBjb1Cxqxi3oNOToHX2vTYoPt9nk1oTSlEUASNcYQ3IPnxvmlSfGcfv8ati\nw1Q6JOMQjKxEdK3MNP0FbgEfbB+ikU7TW8A5p5f2XkGc5VKt6iz3cOK83uT35SQ9\nX5PS3GcKMuYP2XnuTt9MR60C+qUFANQIKjIc8VHw7QKBgQDgUnppM4ksXTuncmh4\nkxDq+kUJt4dMSR0kpkvphMGAZDbuq4S02ZiX2PxLZQrUK1pjWHnEI91v8SFkWeMp\n5fWyCEML2cdZsToTF3vgNuVWi/oRyvDCpIEvJj+ONJd66ruymaRbsts5fI03BZtY\nYVYCYCij0D5eLUwbaFMwbH1SxwKBgQDPyFVd74r7TbXLfe+r+QrXJU4UtE1L/hRo\nvPNY9ZijDT4iKrXogkbtA0hwKx9gdIwYCW8u7lU8ruv+rNEdzB71y5UWBfEkx/IO\n35sghVjQ8b7KSqAv3tnZ6qyoijcbbh4pK7C1nNvqQSLguNBJ3fIrF6GOCwEz7nBK\nYeONc2XddwKBgQCNzRV8cwt/c+BF1Vic/7puD46cudtZKc62YDkUgMshMjhXXy0g\ndXy0YIH71v+lZ1JYApHWnyVXogINwZSL48YQqJBZaW1PEW04rFuuPIV01D9cCAFx\nyTOwbmk2p6AqH0BPgjgXj1RtXoKWCYFNuRn5nneSNg120wONP8F2lt4R+QKBgGPq\nxzpbxa6hKOnJDqbZJKBe/RQxu/XuIaxYKIE/4P2PkbBmb4F2nFq/OGdQJU+B3Bh2\n+PNNgsmiqDOYsRquHLlAA9pKUzLHv5vtZTCXTyVzCrdGeY9rj8Ed+5c0l9ll87UC\noIBFBO+6EOaVmPvccebM/1BJ9HMflvn95qoPsw1zAoGAN0qsO9fC1eHZ2lVO8veS\ndrjxVyzSaP4Is8I2ASM5bqRZ9e9kVPFeZOOF50My/+rgMBpSp0BnCcrwGinc+Azn\nmJSSEC9uZoH+MoNBBl8Yql4+DGgVqIk7elfp0Yk4BUQnv0nVV7QhgzGKgh1HFaWM\nATCuGanHbKlnJw5ZlOCERvk=\n-----END PRIVATE KEY-----\n"""
client_email = "firebase-adminsdk-ms7qb@streamlit-quiz.iam.gserviceaccount.com"
client_id = "101500182292460875153"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-ms7qb%40streamlit-quiz.iam.gserviceaccount.com"
universe_domain = "googleapis.com"




